### ISSUE TITLE
Valid API Key

### ISSUE THREAD

**Issue by FHantke** [sirmammingtonham/futureMAG#7]
Hey @sirmammingtonham 

while scanning Github for repositories that use the Medium API, I stumbled across your Auth Key [here ](https://github.com/sirmammingtonham/futureMAG/blob/e47d2a06073aae36a0abd2e692eef73ec2d627da/tests/bruh.ipynb) and [here](https://github.com/sirmammingtonham/futureMAG/blob/e47d2a06073aae36a0abd2e692eef73ec2d627da/publish.py). It is still active and I would recommend you to delete it from Github as everyone can access your account using it.

Best regards,
Florian

**Comment by sirmammingtonham** [comment]
Thanks Florian, I generated a new key and deleted the old one.
